package br.com.estoqueBr.controller;

public enum SessionsConstants {
	
	CALL_BACK_URL_ON_SUBMIT,
	CALL_BACK_URL_ON_CANCELL,
	CUSTEIO_DTO,
	DESTINO_DTO,
	FABRICANTE_DTO,
	FORNECEDOR_DTO,
	MATERIAL_DTO,
	NOTA_FISCAL_DTO,
	ORDEM_SERVICO_DTO
}
